### ISSUE TITLE
Increase "window_size" for DASH streams

### ISSUE THREAD

**Issue by derrod** [voc/cm#12]
Right now the HLS stream has a DVR window of approximately 9 minutes whereas DASH is limited to 2. This is also high enough to enable the DVR controls in clappr, but too low be actually usable.

A longer DVR window (e.g. 15-30 minutes) is useful in cases where you want to watch a talk with some time shift compared to live (let's say you're 5 minutes late or pause at some point to come back to within a couple minutes).

I'm not sure how that conflicts with RELIVE's purpose since that doesn't seem to be working right now.

File I'm referencing: https://github.com/voc/cm/blob/events/35c3/ansible/roles/relay/files/fanout/dash.py#L90

**Comment by iSchluff** [comment]
We didn't care about live-dvr until now, because the web player couldn't do it, but now with that patched in: https://github.com/voc/streaming-website/commit/46dfa787ecf082b646d73e9948887af20277bc8d I will push the window_size to 10 minutes first and see where we go from there. The only limiting factor here is disk space on some of our edge relays.

**Comment by derrod** [comment]
Thanks, seems to work well so far! I'd like to see a further increase in dvr length in the future, but for now this will do.
